### ISSUE TITLE
Installed correctly but menus aren't working

### ISSUE THREAD

**Issue by niuwle** [stupidusername/bukmark#2]
Hi! I installed this but the links for the menu aren't working, what I'm missing, did all the steps for configuring. Here is my test env http://www.bukmark3.hobs.com.ar/

**Comment by stupidusername** [comment]
It looks like the web server it's not forwarding the request to the index.php script. Check out the official installation guide of Yii2 and take a look on how to configure your web server.

[Installing Yii2](https://www.yiiframework.com/doc/guide/2.0/en/start-installation)

**Comment by niuwle** [comment]
Thanks for the quick response! I also did a XAMP local install and I get to the same error. I added this to the httpd.conf:

# Set document root to be "basic/web"
DocumentRoot "C:\xampp\htdocs\web"

<Directory "C:\xampp\htdocs\web">
    # use mod_rewrite for pretty URL support
    RewriteEngine on
    # If a directory or a file exists, use the request directly
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    # Otherwise forward the request to index.php
    RewriteRule . index.php

    # if $showScriptName is false in UrlManager, do not allow accessing URLs with script name
    RewriteRule ^index.php/ - [L,R=404]

    # ...other settings...
</Directory>

**Comment by stupidusername** [comment]
Try deleting this line:

`RewriteRule ^index.php/ - [L,R=404]`

**Comment by stupidusername** [comment]
It looks like there is an error in the docs.

[Yii2 issue #15490](https://github.com/yiisoft/yii2/issues/15490)
